### ISSUE TITLE
Is GD::Image::copyRotated compatible with libGD 3.0?

### ISSUE THREAD

**Issue by dvdmatt** [lstein/Perl-GD#14] opened 2015-08-07 05:20 UTC
Running Fedora Linux GD::Image::copyRotated() appears to incorrectly throw a version error:

Environment:
matt@aslan:276% cat /etc/fedora-release 
Fedora release 20 (Heisenbug)
matt@aslan:277% rpm -q gd
gd-2.1.0-8.fc20.x86_64
matt@aslan:278% perl_module_version GD GD::Image
GD                      : 2.49
GD::Image           : 2.38
matt@aslan:279% rpm -ql gd | grep libgd
/usr/lib64/libgd.so.3
/usr/lib64/libgd.so.3.0.0

Symptom:
matt@aslan:280% perl rotate_image test.jpg 270
libgd 2.0.33 or higher required for copyRotated support at /home/matt/src/LLS/Graphics.pm line 368.
matt@aslan:281% grep copyRotated LLS/Graphcis.pm
my ($w, $h) = $image->getBounds(); $image->copyRotated($oldimage, $h/2, $w/2, 0, 0, $w, $h, 270);

What additional detail can I provide?

**Comment by dvdmatt** [comment] 2015-08-07 15:18
Upgraded to Fedora22 and see the same issue

matt@aslan:5% cat /etc/fedora-release 
Fedora release 22 (Twenty Two)
matt@aslan:6% rpm -q gd
gd-2.1.1-2.fc22.x86_64
matt@aslan:7% perl_module_version GD GD::Image
GD                      : 2.56
GD::Image           : 2.55
matt@aslan:8% rpm -ql gd | grep libgd
/usr/lib64/libgd.so.3
/usr/lib64/libgd.so.3.0.0
matt@aslan:9% checkWebsite
Building icons and web images
libgd 2.0.33 or higher required for copyRotated support at /home/matt/src/LLS/Graphics.pm line 368.

This application has been working for years with gd 2.x

**Comment by dvdmatt** [comment] 2015-08-07 15:45
Validated that copyRotate90() et.al. are working.

**Comment by rurban** [comment] 2017-04-21 08:42
This was caused by a wrong version check, not honoring 2.1 or 2.2. Should be fixed with 2.57 and 2.58.

**Closed by rurban** 2017-04-21 08:42 UTC
